name: Build Azure Function Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: amplify-jobs-digitalonboarding

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .
